### ISSUE TITLE
Do we need to sign up for Miro and/or Mural?

### ISSUE THREAD

**Issue by emanlove** [SeleniumHQ/sosc#61]
Exploring the Welo space (which I seem to be able to fully explore without having to do any setup; just follow the link from the main page) I see there are some tools on the lower central toolbar: Google Drive, miro and Mural. With miro it appears that one can create a board without signing up. Will we need thought to create a miro account in order to work with others in the OSC? And the same with Mural; do we need to create an account?

**Comment by maaretp** [comment]
You don't need to use the links on bottom - we can use those to share a Miro board for everyone. Instead, if you look at room called Information, you see it has a little folder image with resources attached to it - there is a link to the conference  Miro board. We build our agenda on it, and it is open for anyone. I tweaked Miro rights a bit so that you can join the as guests but it does not allocate you licenses. So no need to create accounts.

**Comment by lana-20** [comment]
![image](https://github.com/SeleniumHQ/sosc/assets/70295997/03d6574e-97cc-4e1a-9fe4-1e13fd8f95c0)
@maaretp thank you, I found it!
